name: Terraform EC2 IDP

on:
  workflow_dispatch:
    inputs:
      action:
        required: true
      instance_name:
        required: false

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: envs

      - name: Terraform Apply
        if: ${{ github.event.inputs.action != 'delete' }}
        run: terraform apply -auto-approve -var-file=../tfvars/instances.tfvars
        working-directory: envs

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'delete' }}
        run: terraform destroy -auto-approve -target=module.ec2["${{ github.event.inputs.instance_name }}"]
        working-directory: envs

      - name: Save Key
        run: terraform output -raw keys > key.pem
        working-directory: envs

      - uses: actions/upload-artifact@v4
        with:
          name: ec2-key
          path: envs/key.pem
